### ISSUE TITLE
Error on startup 1.21.4

### ISSUE THREAD

**Issue by Valve-Anti-Cheat** [Gizmo0oDev/FastNick-Issues#5]
**Describe the bug**
Error spamming in console and nicknames not applying

**To Reproduce**
1. Install on 1.21.4 and start server

**Expected behavior**
To work normally

**Screenshots**
https://imgur.com/a/Hyf7E3D

**Versions (please complete the following information):**
 - Plugin version: Latest
 - Server version: Latest 1.21.4
 - Dependencies version: Latest

**Additional context**

[00:30:40 ERROR]: [FastNick] Unhandled exception occurred in onPacketSending(PacketEvent) for FastNick
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_20_R1/entity/CraftPlayer
        at FastNick-1.1.jar/io.github.gizmo0odev.fastnick.FastNick$2.onPacketSending(FastNick.java:64) ~[FastNick-1.1.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invokeListener(OutboundPacketListenerSet.java:74) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:123) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:123) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invoke(OutboundPacketListenerSet.java:30) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:102) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:528) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.PacketFilterManager.invokeOutboundPacketListeners(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:528) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:44) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:233) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:479) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.network.Connection.send(Connection.java:440) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:296) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:278) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at org.bukkit.craftbukkit.entity.CraftPlayer.setPlayerListName(CraftPlayer.java:594) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at ItemsAdder_4.0.6.jar/itemsadder.m.qc.aH(SourceFile:241) ~[ItemsAdder_4.0.6.jar:?]
        at ItemsAdder_4.0.6.jar/itemsadder.m.qc.p(SourceFile:177) ~[ItemsAdder_4.0.6.jar:?]
        at ItemsAdder_4.0.6.jar/itemsadder.m.afd.run(SourceFile:81) ~[ItemsAdder_4.0.6.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1659) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1529) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer
        ... 27 more
[00:30:40 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket@70c5610b[
    actions=[UPDATE_DISPLAY_NAME]
    entries=[Entry[profileId=5d8efe40-760d-402d-9832-746e227587bc, profile=com.mojang.authlib.GameProfile@22903af4[id=5d8efe40-760d-402d-9832-746e227587bc,name=digsyy,properties={textures=[Property[name=textures, value=ewogICJ0aW1lc3RhbXAiIDogMTczNTA4NjM5OTExMSwKICAicHJvZmlsZUlkIiA6ICI1ZDhlZmU0MDc2MGQ0MDJkOTgzMjc0NmUyMjc1ODdiYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJkaWdzeXkiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjE5ZTk5YmFjZGI2NDgwOTNjMzhmYmE4MTVjMDg0NGYwYWRiZWQ4NjljMTRiYjIxYjMwMDZjYzdiNGRkYTczNCIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9, signature=t6Gul61rSnpGIgJM3ZHyEhko6GDXnLn8SnNmbpf2c9rRhHuZ1t1Td9aPtJOpyqCLkQszLk52yehv4t+itq8m8Xmy4L+3sNWiRtXl8Z/SEXcQPY1tHr1WfQSgB38qwQx7FMc+fJgDGMz11lK86RzDYV13bZ4NndYk7s3euWYzUKKWbnMx9MHeXJuBgdqEpEytYfFKq/ybWJ6BKt9SVeckEQ2ndwd6amS76krkTPPKZUX/nFJH3NCvxCQjTLj13ceDKt6YVZTDIDt5eNLf3aeEvUQ0KRmLUAn9ADPA1xiDdslzmgzXUqpLwyrTOTz3BOLHvo9+qDzkTL5f98xws+Fc1WBZk7HSMf0r6JOJZNAD+eQagE14OfbLWm7DLAkBLrpVlJ7sDvPn6MN8k8YxIpphSfnSupn5UxPrl9+oVeb+q6MK9CYluxXumn/l1inU/GxfxPSq1/iaWdNl/TYrtSTonQcaXTAkkp2eNqcH96WeL82JS4qIUapspQdB8hySDqthUdiiOIYuSdeOBMnvEH/+Qvp5kxY8pJQABMDiEnfiawkUoRc2QYmeqtl76YjAizumcN8XqptB55KiAjfrlY8Yba7X24Xtry9gskDfxKFodTJaEwUiSPN/csgyciPpFYuFWZC6zWUCgOL42mmHBsTVrKQolv1rR5MlBkEnF4hKkx0=]]}], listed=true, latency=56, gameMode=CREATIVE, displayName=empty[siblings=[literal{Digsy}[style={color=white,!bold,!italic,!underlined,!strikethrough,!obfuscated}]]], showHat=true, listOrder=0, chatSession=null]]
  ]

**Comment by Valve-Anti-Cheat** [comment]
Doesn't work on 1.21.8 either. Bought this plugin and still never have been able to use.
